CREATE TABLE purchase(
                         id int primary key generated always as identity,
                         name varchar(100) not null unique
);

CREATE TABLE orders(
                       id int primary key generated always as identity,
                       name varchar(100) not null,
                       lastname varchar(100) not null,
                       age int not null,
                       purchase_item varchar(100) references purchase(name),
                       count integer not null,
                       amount double precision not null,
                       orders_date_time timestamp not null
);

insert into purchase(name) values('Телевизор');
insert into purchase(name) values('Смартфон');
insert into purchase(name) values('Соковыжималка');
insert into purchase(name) values('Наушники');
insert into purchase(name) values('Клавиатура');

select * from purchase;


CREATE TABLE sign(
                     id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                     username varchar(100) not null,
                     year_of_birth int not null,
                     password varchar not null
);

INSERT INTO sign (username, year_of_birth, "password") VALUES ('user', 2000, 'user');